base_url: /
domain: joshfinnie.com
author: Josh Finnie
description: Josh Finnie's Personal Website and Blog
email: josh@jfin.us
subtitle:
title: Josh Finnie dot com
post_limit: false
posts_url: /blog/<title>/
analytics: UA-250621-15
feed: true
social:
    dribbble:
    facebook:
    github:
    google_plus:
    lastfm:
    stack_overflow:
    steam:
    twitter:
pygmentize: true
jinja:
    extensions:
        - jinja2.ext.loopcontrols
tag_layout: tag.html
tags_url: /tags/
